pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    def commit_id
    stages {
         stage('Clone repository github') { 
            steps { 
                script{
                checkout scm
                sh "git rev-parse --short HEAD > .git/commit-id"
                commit_it = reaFile('.git/commit-id').trim()
                }
            }
        }
        // stage('Docker Build') {
    	   //  agent any
        //       steps {
      	 //        sh 'docker build -t jenkins-pipeline/Dockerfile:latest .'
        //         }
        //     }      
        }
    }


