pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository github') { 
            steps { 
                script{
                checkout scm
                }
            }
        }
        stage('Docker Build') {
    	    agent any
              steps {
      	        sh 'docker build -t jenkins-pipeline/Dockerfile:latest .'
                }
            }      
        }
    }


