node {  
     def commit_id
     stage('Checkout') { 
         checkout scm
    }
    stage('Build') { 
        // 
    }
    stage('Test') { 
        // 
    }
    stage('Deploy') { 
        // 
    }
}
